plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id
base { archivesName = "${mod_id}-neoforge-1.21.1" }

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.248'
    runs {
        client { client() }
        server { server() }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
    maven { name = 'NeoForge'; url = 'https://maven.neoforged.net/releases/' }
}

dependencies {
    compileOnly files('../Q-shop/build/libs/qshop-1.2.3.jar')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    inputs.properties([
            mod_id: mod_id,
            mod_name: mod_name,
            mod_version: mod_version,
            mod_license: mod_license,
    ])
    filesMatching('META-INF/neoforge.mods.toml') {
        expand mod_id: mod_id, mod_name: mod_name, mod_version: mod_version,
                mod_license: mod_license
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) { from components.java }
    }
}
